
server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://cylt-mysql:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  redis:
    database: 0
    host: cylt-redis
    port: 6379
  rabbitmq:
    host: cylt-rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
        prefetch: 5
  application:
    name: cylt-main
  cloud:
    nacos:
      server-addr: cylt-mysql:8848
logging:
  level:
    root: info
  file:
    name: log/main.log

