version: '3'

services:
  web:
    image: httpd
    container_name: cylt_web
    restart: always
    ports:
    - "80:80"
    networks:
      cyltnet:
        aliases:
        - web
    volumes:
    - ../cylt-vue/dist:/usr/local/apache2/htdocs/
    - ./httpd/conf:/usr/local/apache2/conf
  mysql:
    image: docker.io/mysql:5
    restart: always
    ports:
    - 3306:3306
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456789"
      MYSQL_USER: 'wuyh'
      MYSQL_PASS: '123456789'
    volumes:
      - "./mysql/db:/var/lib/mysql"
      - "./mysql/conf:/etc/my.cnf"
      - "./mysql/init:/docker-entrypoint-initdb.d/"
    networks:
      cyltnet:
        aliases:
        - cylt-mysql
  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    image: "rabbitmq:3-management"
    restart: always
    volumes:
    - "./rabbitmq/data:/var/lib/rabbitmq"
    - "./rabbitmq/log:/var/log/rabbitmq/log"
    ports:
    - "15672:15672"
    - "4369:4369"
    - "5672:5672"
    - "25672:25672"
    networks:
      cyltnet:
        aliases:
        - cylt-rabbitmq
  redis:
    image: redis
    container_name: redis
    hostname: redis
    restart: always
    ports:
    - 6379:6379
    networks:
      cyltnet:
        aliases:
        - cylt-redis
    volumes:
    - "./redis/data:/data"
    - "./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf"
    - "./redis/logs:/logs"
  main:
    container_name: cylt_main
    build: ../cylt-main/
    restart: always
    volumes:
    - "./java/log:/log"
    ports:
    - "8888:8888"
    networks:
      cyltnet:
        aliases:
        - cylt-main
  log:
    container_name: cylt_log
    build: ../cylt-log/
    restart: always
    volumes:
    - "./java/log:/log"
    ports:
    - "8010:8010"
    networks:
      cyltnet:
        aliases:
        - cylt-log
  sys:
    container_name: cylt_sys
    build: ../cylt-sys/
    restart: always
    ports:
    - "8002:8002"
    volumes:
    - "./java/log:/log"
    networks:
      cyltnet:
        aliases:
        - cylt-log
  nacos:
    image: nacos/nacos-server
    container_name: nacos
    environment:
    - MODE=standalone
    - SPRING_DATASOURCE_PLATFORM=mysql
    - MYSQL_SERVICE_HOST=cylt-mysql
    - MYSQL_MASTER_SERVICE_PORT=3306
    - MYSQL_SERVICE_USER=root
    - MYSQL_SERVICE_PASSWORD=123456789
    - MYSQL_SERVICE_DB_NAME=nacoss
    - JVM_XMS=512m
    - JVM_MMS=320m
    volumes:
    - ./standalone-logs/:/home/nacos/logs
    - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    depends_on:
    - mysql
    ports:
    - "8848:8848"
    - "9848:9848"
    - "9555:9555"
    restart: always
    networks:
      cyltnet:
        aliases:
        - cylt-nacos
networks:
  cyltnet:
